"""
This type stub file was generated by pyright.
"""

from typing import Any, Literal

import click
from gtts import __version__

CONTEXT_SETTINGS = ...
LOGGER_SETTINGS = ...
log = ...

def sys_encoding() -> Literal["utf8"]:
    """Charset to use for --file <path>|- (stdin)"""
    ...

def validate_text(ctx: Any, param: Any, text: str) -> Any:
    """Validation callback for the <text> argument.
    Ensures <text> (arg) and <file> (opt) are mutually exclusive
    """
    ...

def validate_lang(ctx: Any, param: Any, lang: Any) -> str:
    """Validation callback for the <lang> option.
    Ensures <lang> is a supported language unless the <nocheck> flag is set
    """
    ...

def print_languages(ctx: Any, param: Any, value: Any) -> None:
    """Callback for <all> flag.
    Prints formatted sorted list of supported languages and exits
    """
    ...

def set_debug(ctx: Any, param: Any, debug: Any) -> None:
    """Callback for <debug> flag.
    Sets logger level to DEBUG
    """
    ...

@click.command(context_settings=CONTEXT_SETTINGS)
@click.argument("text", metavar="<text>", required=False, callback=validate_text)
@click.option(
    "-f",
    "--file",
    metavar="<file>",
    type=click.File(encoding=sys_encoding()),
    help="Read from <file> instead of <text>.",
)
@click.option("-o", "--output", metavar="<file>", type=click.File(mode="wb"), help="Write to <file> instead of stdout.")
@click.option("-s", "--slow", default=False, is_flag=True, help="Read more slowly.")
@click.option(
    "-l",
    "--lang",
    metavar="<lang>",
    default="en",
    show_default=True,
    callback=validate_lang,
    help="IETF language tag. Language to speak in. List documented tags with --all.",
)
@click.option(
    "-t",
    "--tld",
    metavar="<tld>",
    default="com",
    show_default=True,
    is_eager=True,
    help="Top-level domain for the Google host, i.e https://translate.google.<tld>",
)
@click.option(
    "--nocheck",
    default=False,
    is_flag=True,
    is_eager=True,
    help="Disable strict IETF language tag checking. Allow undocumented tags.",
)
@click.option(
    "--all",
    default=False,
    is_flag=True,
    is_eager=True,
    expose_value=False,
    callback=print_languages,
    help="Print all documented available IETF language tags and exit.",
)
@click.option(
    "--debug",
    default=False,
    is_flag=True,
    is_eager=True,
    expose_value=False,
    callback=set_debug,
    help="Show debug information.",
)
@click.version_option(version=__version__)  # type:ignore
def tts_cli(text: str, file: Any, output: Any, slow: Any, tld: Any, lang: Any, nocheck: Any) -> None:
    """Read <text> to mp3 format using Google Translate's Text-to-Speech API
    (set <text> or --file <file> to - for standard input)
    """
    ...
